import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Nav from "@/components/sidebar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          <main className="w-full h-[100vh] overflow-scroll p-10">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
